version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - 5432:5432
  redis:
    image: redis:5-alpine
    ports: 
      - 6379:6379

volumes:
  postgres_data_dev: