# Generated by Django 2.2.5 on 2019-10-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='secret_key',
            field=models.CharField(default='invalid secret key', max_length=24),
            preserve_default=False,
        ),
    ]
