# Generated by Django 2.2.5 on 2019-10-22 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('museum', '0002_museum_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='hidden_users',
            field=models.ManyToManyField(related_name='hidden_museums', to=settings.AUTH_USER_MODEL),
        ),
    ]
