# Generated by Django 2.2.5 on 2019-10-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191030_1504'),
        ('museum', '0003_museum_hidden_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='profiles',
            field=models.ManyToManyField(to='user.UserProfile'),
        ),
    ]
