# Generated by Django 2.2.5 on 2019-11-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_museum_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
