# Generated by Django 2.2.5 on 2019-11-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191030_1504'),
        ('museum', '0005_auto_20191113_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museum',
            name='hidden_users',
        ),
        migrations.AddField(
            model_name='museum',
            name='hidden_profiles',
            field=models.ManyToManyField(related_name='hidden_museums', to='user.UserProfile'),
        ),
    ]
