# Generated by Django 2.2.5 on 2020-02-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0007_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='profiles',
            field=models.ManyToManyField(related_name='groups', to='user.UserProfile'),
        ),
    ]
