# Generated by Django 2.2.5 on 2020-02-11 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('museum', '0008_auto_20200205_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='leaders',
            field=models.ManyToManyField(related_name='lead_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
