# Generated by Django 2.2.5 on 2019-10-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_museum_secret_key'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawGameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.CharField(max_length=24, unique=True)),
                ('museum_secret_key', models.CharField(max_length=24)),
                ('museum_id', models.IntegerField()),
                ('simulator_id', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('num_of_rolls', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='num_of_rolls',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='score',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='start_time',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='simulator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='museum.Simulator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameresult',
            name='raw_result',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.RawGameResult'),
            preserve_default=False,
        ),
    ]
