# Generated by Django 2.2.5 on 2019-10-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20191006_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawgameresult',
            name='qr_token',
            field=models.CharField(max_length=24),
        ),
    ]
