# Generated by Django 2.2.5 on 2019-10-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191006_1247'),
        ('game', '0003_auto_20191006_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
            preserve_default=False,
        ),
    ]
