# Generated by Django 2.2.5 on 2019-10-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gameresult_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='user',
        ),
    ]
