# Generated by Django 2.2.5 on 2020-01-30 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200130_1119'),
        ('game', '0005_remove_gameresult_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawgameresult',
            old_name='qr_token',
            new_name='u1_qr_token',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='profile',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='copilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copilot_set', to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='pilot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pilot_set', to='user.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawgameresult',
            name='u2_qr_token',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
