# Generated by Django 2.2.5 on 2020-01-30 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200130_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawgameresult',
            old_name='simulator_id',
            new_name='sim_id',
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='copilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copilot_set', to='user.UserProfile'),
        ),
    ]
