# Generated by Django 2.2.5 on 2020-01-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200130_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawgameresult',
            name='u2_qr_token',
            field=models.CharField(blank=True, default='', max_length=24),
            preserve_default=False,
        ),
    ]
