# Generated by Django 2.2.5 on 2020-03-02 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20200131_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='raw_result',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 17, 43, 1, 338765, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameresult',
            name='num_of_rolls',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameresult',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameresult',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 17, 43, 14, 986931, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RawGameResult',
        ),
    ]
