# Generated by Django 2.2.5 on 2019-10-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='qr_token',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
