# Generated by Django 2.2.5 on 2019-10-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_museum_secret_key'),
        ('user', '0004_auto_20191009_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='museum_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.Museum'),
        ),
    ]
