# Generated by Django 2.2.5 on 2019-10-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191011_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='museum_origin',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_before_user',
            field=models.BooleanField(default=True),
        ),
    ]
