# Generated by Django 2.2.5 on 2020-01-30 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_passreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passreset',
            name='email',
        ),
        migrations.AddField(
            model_name='passreset',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passreset',
            name='code',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
