# Generated by Django 2.2.5 on 2020-02-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200130_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temp_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
