# Generated by Django 2.2.5 on 2020-02-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userprofile_temp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirm_token',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
