# Generated by Django 2.2.5 on 2020-03-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200218_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='temp_name',
            new_name='display_name',
        ),
    ]
