# Generated by Django 2.2.5 on 2020-11-11 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0013_auto_20200303_1426'),
        ('museum', '0009_group_leaders'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copilot_event', to='user.UserProfile')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.Event')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_event', to='user.UserProfile')),
                ('simulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Simulator')),
            ],
        ),
    ]
