# Generated by Django 2.2.5 on 2020-11-11 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='gameevent',
            name='id',
        ),
        migrations.AddField(
            model_name='gameevent',
            name='game_event_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='is_claimed',
            field=models.BooleanField(default=False, verbose_name='Event is claimed and confirmed'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pilot_event', to='user.UserProfile'),
        ),
    ]
