# Generated by Django 2.2.5 on 2020-04-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
