# Generated by Django 2.2.5 on 2020-04-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20200302_1243'),
        ('badges', '0004_auto_20200408_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='players',
        ),
        migrations.AddField(
            model_name='badge',
            name='game_results',
            field=models.ManyToManyField(to='game.GameResult'),
        ),
    ]
