# Generated by Django 2.2.5 on 2020-04-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0005_auto_20200410_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
