# Generated by Django 2.2.5 on 2020-04-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_badge_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='icon_incomplete',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
