# Generated by Django 2.2.5 on 2020-04-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20200302_1243'),
        ('badges', '0007_badge_icon_incomplete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='game_results',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='icon',
        ),
        migrations.CreateModel(
            name='BadgeTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_number', models.IntegerField()),
                ('icon', models.URLField()),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badges.Badge')),
                ('game_results', models.ManyToManyField(to='game.GameResult')),
            ],
            options={
                'unique_together': {('badge', 'tier_number')},
            },
        ),
    ]
